config/routes.rb
Rails.application.routes.draw do
  resources :users, only: %i[new create]
  resources :questions do
    resources :answers, extend: %i[new show]
  end

  root 'pages#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  validates :body, presence: :true, length: { minimum:5 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
    has_many :answers, dependent: :destroy
    validates :title, presence: true, length: {minimum: 2}
    validates :body, presence: true, length: {minimum: 2}
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_question
  before_action :set_answer, extend: :create

  def update
    if @answer.update answer_params
      flash[:success] = 'Answer updated'
      redirect_to question_path(@question, anchor: "answer-#{@answer.id}")
    else
      render :edit
    end
  end

  def edit; end

  def create
    @answer = @question.answers.build answer_params
    if @answer.save
      flash[:success] = "Answer created"
      redirect_to question_path(@question)
    else
      flash[:danger] = "Answer doesn`t created"
      @answers = @question.answers.order created_at: :desc
      render "questions/show"
    end
  end

  def destroy
    if @answer.destroy
      flash[:success] = "Question deleted"
    else
      flash[:danger] = "Something went wrong"
    end
    redirect_to question_path(@question)
  end

  private

  def answer_params
    params.required(:answer).permit(:body)
  end

  def set_question
    @question = Question.find_by id: params[:question_id]
  end

  def set_answer
    @answer = @question.answers.find params[:id]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :current_user

  private

  def current_user
    @current_user = User.find_by( id: session[:user_id]) if session[:user_id].present?
  end

  def user_sign_in?
    current_user.present?
  end

  helper_method :current_user, :user_sign_in?
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[edit update show destroy]

  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new question_params
    if @question.save
      flash[:success] = "Question created"
      redirect_to questions_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @question.update question_params
      flash[:success] = "Question updated"
      redirect_to questions_path
    else
      render :new
    end
  end

  def destroy
    if @question.destroy
      flash[:success] = "Question deleted"
    else
      flash[:danger] = "Something went wrong"
    end
    redirect_to questions_path
  end

  def show
    @answer = @question.answers.build
    @answers = @question.answers.order created_at: :desc
  end

  private

  def question_params
    params.required(:question).permit(:title, :body)
  end

  def set_question
    @question = Question.find_by id: params[:id]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome #{@user.name}"
      redirect_to questions_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_tab(title, url, options = {})
    current_page = options.delete :current_page
    css_class = current_page == title ? 'fw-bold' : ''
    options[:class] = options[:class] ? "#{options[:class]} #{css_class}" : css_class

    link_to title, url, options
  end

  def currently_at(current_page)
    render partial: 'shared/menu', locals: { current_page: current_page }
  end

  def full_title(page_title = '')
    base_title = 'OForum'
    if page_title.present?
      "#{page_title} | #{base_title}"
    else
      base_title
    end
  end
end

app/views/answers/_answer.html.erb
<div class="card mt-3" id="answer-<%= answer.id %>">
  <section class="card-body">
    <p class="lead mt-3">
      <%= answer.body %>
      <br>
    </p>
    <time class="mt-4">
      <small><%=answer.created_at %></small>
      <br>
    </time>
    <%= link_to "Delete", question_answer_path(question, answer), data: {method: :delete, confirm: "Are you sure?"}, class: "btn btn-danger btn-xs mt-3"%>
    <%= link_to "Edit", edit_question_answer_path(question, answer), class: "btn btn-info btn-xs mt-3"%>
  </section>
</div>

app/views/answers/_form.html.erb
<%= render 'shared/errors', object: @answer %>

<%= form_with model: [@question, @answer] do |f|%>
  <div class="card">
    <div class="card-body">
      <div class="row mt-2">
        <div class="col-sm-2">
          <%= f.label :body, class: "col-form-label" %>
        </div>
        <div class="col-sm-10">
          <%= f.text_area :body, class: "form-control" %>
        </div>
      </div>
      <%= f.submit "Submit answer", class: "btn btn-primary mt-2"%>
    </div>
  </div>
<% end %>

app/views/answers/edit.html.erb
<% provide :page_title, 'Edit answer' %>
<%= currently_at 'Answer' %>

<h1>Edit answer</h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title><%= full_title(yield(:page_title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield :main_menu %>

    <main class="container mt-3">

      <% flash.each do |k, v| %>
        <%= tag.div v, class: "alert alert-#{k}", role: 'alert'%>
      <% end %>

      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/index.html.erb
<% currently_at 'Home' %>

<h1>Welcome</h1>

&copy; @Korosh <%= Time.now.year %>

app/views/questions/_form.html.erb
<%= render "shared/errors", object: @question %>
    
<%= form_with model: @question do |f|%>
    <div class="row mt-4">
        <div class="col-sm-2 col-form-label">
            <%= f.label :title%>
        </div>
        <div class="col-sm-10">
            <%= f.text_field :title, class: "form-control"%>
        </div>
    </div>

    <div class="row mt-4">
        <div class="col-sm-2 col-form-label">
            <%= f.label :body%>
        </div>
        <div class="col-sm-10">
            <%= f.text_area :body, class: "form-control"%>
        </div>
    </div>
	<%= f.submit "Submit", class: "mt-4 btn btn-primary"%>
<% end %>

app/views/questions/_question.html.erb
<article class="card mt-3">
  <div class="card-body">
    <h2><%= question.title %></h2>

    <section class="mt-4 card-text">
      <p>
        <%= truncate question.body, length: 150, omission: '...(continue)'  %>
      </p>
      <time><small><%= question.created_at %></small></time>
    </section>

    <div class="mt-2">
      <%= link_to "Show", question_path(question), class: "btn btn-primary"%>
      <%= link_to "Edit", edit_question_path(question), class: "btn btn-secondary"%>
      <%= link_to "Delete", question_path(question), data: {method: :delete, confirm: "Are you sure?"}, class: "btn btn-danger" %>
    </div>
  </div>
</article>

app/views/questions/edit.html.erb
<% provide :page_title, 'Edit question' %>
<% currently_at 'Questions' %>
<h1>Edit question</h1>

<%= render 'form' %>

app/views/questions/index.html.erb
<% provide :page_title, 'Questions' %>
<% currently_at 'Questions' %>
<h1>Questions</h1>

<%= link_to "Create question", new_question_path, class: "mt-3 btn btn-success"%>

<%= render @questions %>

app/views/questions/new.html.erb
<% provide :page_title, 'New question' %>
<%= currently_at 'Questions' %>
<h1>New Question</h1>

<%= render 'form' %>

app/views/questions/show.html.erb
<% provide :page_title, 'Show question' %>
<%= currently_at 'Questions' %>

<h1><%= @question.title %></h1>

<section>
	<p class="lead mt-3">
		<%= @question.body %>
		<br>
	</p>
	<time class="mt-4">
		<small><%= @question.created_at %></small>
	</time>
</section>
<div class="mt-2">
	<%= link_to "Edit", edit_question_path(@question), class: "btn btn-secondary"%>
	<%= link_to "Delete", question_path(@question), data: {method: :delete, confirm: "Are you sure?"}, class: "btn btn-danger" %>
</div>
<hr class="my-3">
<h2>Answers</h2>

<%= render 'answers/form' %>
<%= render partial: 'answers/answer', collection: @answers, as: :answer, locals: {question: @question}%>

app/views/shared/_errors.html.erb
<% if object.errors.full_messages.any? %>
    <div class="alert alert-danger">
        <ul class="mb-0">
            <% object.errors.full_messages.each do |error|%>
                <li><%=error%></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/shared/_menu.html.erb
<%= provide :main_menu do %>
  <header class="p-3 bg-dark text-white">
    <div class=container>
      <nav class="d-flex flex-wrap justify-content-between">
        <ul class="nav col-12 col-lg-auto">
          <li><%= nav_tab 'Home', root_path,
                          class: "nav-link px-2 text-white",
                          current_page: current_page %></li>
          <li><%= nav_tab 'Questions', questions_path,
                          class: "nav-link px-2 text-white",
                          current_page: current_page %></li>
        </ul>
        <ul class="nav col-12 col-lg-auto">
          <% if user_sign_in? %>
            <li class="nav-link px-2 text-white">
              <span><%= @current_user.name %></span>
            </li>
          <% else %>
            <li><%= nav_tab 'Sign Up', new_user_path,
                            class: "nav-link px-2 text-white",
                            current_page: current_page %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>
<% end %>

app/views/users/_form.html.erb
<%= render "shared/errors", object: @user %>

<%= form_with model: @user do |f| %>
  <div class="row mt-4">
    <div class="col-sm-2 col-form-label">
      <%= f.label :email %>
    </div>
    <div class="col-sm-10">
      <%= f.text_field :email, placeholder: "E-mail", class: "form-control form-control-lg" %>
    </div>
  </div>
  <div class="row mt-4">
    <div class="col-sm-2 col-form-label">
      <%= f.label :name %>
    </div>
    <div class="col-sm-10">
      <%= f.text_field :name, placeholder: "Name", class: "form-control" %>
    </div>
  </div>
  <div class="row mt-4">
    <div class="col-sm-2 col-form-label">
      <%= f.label :password %>
    </div>
    <div class="col-sm-10">
      <%= f.password_field :password, class: "form-control" %>
    </div>
  </div>
  <div class="row mt-4">
    <div class="col-sm-2 col-form-label">
      <%= f.label :password_confirmation %>
    </div>
    <div class="col-sm-10">
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
  </div>
  <%= f.submit "Register", class: "mt-4 btn btn-primary" %>
<% end %>

app/views/users/new.html.erb
<% provide :page_title, 'Registration' %>
<%= currently_at 'Sign Up' %>

<h1>Registration</h1>

<%= render 'form' %>